### ISSUE TITLE
Possible error in transaction error messages.

### ISSUE THREAD

**Issue by WillRubin** [bvinc/go-sqlite-lite#14]
I keep seeing the error message stating ..."additionally rolling back transaction failed" when getting an error in a transaction. It the database it appears the rollback does work properly. Is it possible there is just a "reporting" logic error in the code? My thinking is in the "WithTx" like code blocks.

For example the function:
```
func (c *Conn) WithTx(f func() error) error {
	if err := c.Begin(); err != nil {
		return fmt.Errorf("failed to begin transaction: %v", err)
	}
	// Perform work inside the transaction
	err := f()
	if err != nil {
		err2 := c.Rollback()
		if err2 != nil {
			return err
		}
		return fmt.Errorf("%v, additionally rolling back transaction failed: %v", err, err2)
	}
	if err = c.Commit(); err != nil {
		return fmt.Errorf("failed to commit transaction: %v", err)
	}
	return nil
}
```
Shouldn't the "return fmt.Errorf("%v, additionally rolling back transaction failed: %v", err, err2)" line be swapped with the "return err" line two lines prior?

**Comment by bvinc** [comment]
You're right.  I just accepted a pull request that fixes this.  Sorry I didn't get to it sooner.  Thanks!
