### ISSUE TITLE
RowMap Stmt.Scan documentation

### ISSUE THREAD

**Issue by ifraixedes** [bvinc/go-sqlite-lite#19]
From the docs of [Stmt.Scan](https://godoc.org/github.com/bvinc/go-sqlite-lite/sqlite3#Stmt.Scan)

> Scan retrieves data from the current row, storing successive column values into successive arguments. If the last argument is an instance of RowMap, then all remaining column/value pairs are assigned into the map. The same row may be scanned multiple times. Nil arguments are silently skipped. https://www.sqlite.org/c3ref/column_blob.html

I haven't been able to figure out where `RowMap` type is defined.
Please can you point me to it?

Thanks.

**Comment by bvinc** [comment]
Thanks for pointing this out.  The reference to `RowMap` was left behind from the original project that `go-sqlite-lite` was forked from.  I've removed the reference.
