### ISSUE TITLE
Error with log

### ISSUE THREAD

**Issue by crosslogic** [bvinc/go-sqlite-lite#4]
Trying the package and got this error:

`# github.com/bvinc/go-sqlite-lite/sqlite3
/tmp/go-build295887014/b071/_x007.o: En la función `fts5Bm25GetData':
../../../github.com/bvinc/go-sqlite-lite/sqlite3/lib/sqlite3.c:193601: referencia a `log' sin definir
collect2: error: ld returned 1 exit status
FAIL	bitbucket.org/marcos19/horarios [build failed]
`

**Comment by bvinc** [comment]
Thank you so much for the bug report.  I set up travis for Linux and OSX and appveyor for Windows.  I was able to reproduce the problem you were having on Linux.  Adding `-lm` to the `LDFLAGS` for Linux fixed it.  Let me know if you have any further problems.
